sudo: required
language: go
services:
- docker
go:
- master
branches:
  only:
  - master
  - develop
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
  global:
  - secure: A9+sEiU+8hNwPqYsactAwCoRac7y6iaZTQ57lzq4vLMqRFlTJVU5g6MBeEVaQP7+uRHKdYrPaHiC38I/mRFRCTYkIKYbsTjCvYxKb4zmbJ32TxAV+ciam63g5DH3WwxV/jhyQtowCrqOhvjIlzJ9YjIv4yScuhK8Aqqgk7QdsqcQQF6TEoqa+5fkPIk/lnBGoORXfX1paMcm07uDVje+QoIDUsg7LYkxbRzw59HIAzyZ8VWbOPyYP+CoYkBgALRluoHWIrdPZV4yraSzA6/ju/5FdMY8hRmMsEzzCORA87BU0wpJUcUpOhGxZow7PHAdvRd54SX9YVWwkAIpzRxPcFqpkte4815XvO/QaVMg6q76sw3inAXk6RrtWC73fL8+bSu3mvnun0WzFdvKt37jz4/R5kMZiSN6cHgN6KuhF1J9HhAlwe0k/WcsKgQbIN1+e8jH9XHUc+CS5rj3sC3k82QVzESwv12kl6QE6SHTrkqZOiHkPyS0EiwwYIcv4RA+yLqgAgotfulMmw8piS/GQN9iOxZ2YltDfBtajb5/5dCuzhmxklBV7jf0uZgaIMMCitc/3z0JeF4AmzC/3EVzi0v403+tmUD/d0MfuvB62NIl+7LaEx1mnfiEQeaJdknDZetIfHXE47qS50/7Xh1wfeFw0Ur5vhgXpdXUpaMYoF8=
  - GCR_HOSTNAME=us.gcr.io
  - GCP_PROJECT_ID=superego-173310
  - GCP_PROJECT_NAME=superego
  - IMAGE_NAME=superego
  - GCP_COMPUTE_ZONE=us-central1-a
  - GCP_CLUSTER_NAME=superego-cluster
before_install:
- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
- export GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/superego-b60ee40757c8.json
- openssl aes-256-cbc -K $encrypted_457358ef82be_key -iv $encrypted_457358ef82be_iv
  -in superego-b60ee40757c8.json.enc -out $GOOGLE_APPLICATION_CREDENTIALS
  -d
- gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
install:
- go get github.com/golang/dep/cmd/dep
- dep ensure
- go get golang.org/x/tools/cmd/cover
- go get github.com/modocache/gover
- go get github.com/mattn/goveralls
- gcloud config set project $GCP_PROJECT_ID
script:
- go list -f '{{if len .TestGoFiles}}"go test -coverprofile={{.Dir}}/.coverprofile
  {{.ImportPath}}"{{end}}' ./... | xargs -L 1 sh -c
- gover
- "$HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
  -repotoken $COVERALLS_TOKEN"
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "dev";
  fi`
- bash ./hack/build.sh "${GCR_HOSTNAME}/${GCP_PROJECT_ID}/${IMAGE_NAME}" $TAG
after_success:
- gcloud docker -- push ${GCR_HOSTNAME}/${GCP_PROJECT_ID}/${IMAGE_NAME}:${TAG}
notifications:
  slack:
    rooms:
    - secure: GoHaeIErGFR0wbtMDYHt57cd6Bllw9DLrLr3lAU5Rv0zAp8PUcAIecYsbYcy2BisS/jUYdcqmxX2aP6KZTQXEmy7sAJOYcIvZ/6Mnep472o+jA5ymHbn3Hbx6mxor/XZ65pgkggni1DhRHYZg2WjUaKk5Qziutb8WRbZNOZ4R7wXEBLbW00pAQuqwDjS8eKnXBtkDicGi6V02VSuK029N/gGy8Lot+kaje+pmgeU5V2Py01zC+cKivkvDtjyhsL1Eb7g7XKN0q42M0c3YOnwVh/6WxlSu8pOtLkimGhzH+/WzSdSItmxYgWTQpjj0zmcWzt715nHk4ngteGc5h2SRE0eW4GonNMfSOle+aJtYV09GKX/7QRmv0M/wjEA8IMvkKrHOAMQOxTqJqBxwgk9we+N6FURzAIvtyt6vNEKoWGDfr+2lEWnS5Te9eXH1RIYmRhRJADoCtx98iGstK9YF7OsCa9iZ7STiCxasChcoDjAQFFN7EgR26gjcU0NqHQLqElPxCyqeyL5mF/2dJm/k4C1YOJVwtX71GSZlC+PzKzWsY+I1hrhwap1FAr8GJV43U8dhd7UR5oAubN9TohTND4O+7CyJatycqDS5QTZHl74kuhUEwVfcXQCi0heCw4CUWL1zTcQL5cdhVzVy4gTJkMRunamH8LcyFMH/D8bg9U=
    on_success: change
    on_failure: always
