sudo: required
language: go
services:
- docker
go:
- master
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
  global:
  - secure: w9JjcJVAh9yOPJcX3JQyc0XebL0ednsTw4Z9b2tKdJD70yDKPBGqxcFPZTsPyRgKgHu2XTUnqoO66JZTRsCJ5aQTGh/qDWVeH50m+QKKC/r6AvIVeFIRYpj2xbVDVGQ+ZnDVIo7Z9n0Ua3j6CwE7Fh1lkAYVOr7GWu3pcLMWqFHqeefjc1CbPntiwiYb6FcT+xoMqH5L6HusLcIAi32WB8X/zQlX9clsQDFe3VJbigjwcCU+ad0awLwV7bEN5e0Jq96X19YYvLNm0DUL3A+aRJ94+PdvQEkrJgHSPNXX028wV8nZ6OCteYWbip1b6fPbjsNpnhrj0j7QIGUEZq0KnOUiF1/jgBZ5nPnLOv++WQkRv2rL21yjaCAgmHsykl+yxgQFtUrT7QJ2KVLXl0RrMr9jpq5gCfaZ0wO31UMF5fllMwOTv5bFTfSqWbrAjLIka9dN2rRQEwgZ3413udtkycHShl1bheMpd2DXUOL9gSA36OYKb49QQSkYQ9/SH3EWFkbFw5IS2Y8p0zdXbRvrqrv5lx9tBSRhuGa1NQEhi0GVQz+7+2FGDoP+WnuWDSTrVvL/6P8bP6uniOY06YGr4rjhP1KpjylMGIG4ayeQniyB0Sky6oT76WGr2cTwP659OwCZBtJcJ51SL/Aai3fmAi3yybKKUMtpuehM99i4np8=
  - secure: A9+sEiU+8hNwPqYsactAwCoRac7y6iaZTQ57lzq4vLMqRFlTJVU5g6MBeEVaQP7+uRHKdYrPaHiC38I/mRFRCTYkIKYbsTjCvYxKb4zmbJ32TxAV+ciam63g5DH3WwxV/jhyQtowCrqOhvjIlzJ9YjIv4yScuhK8Aqqgk7QdsqcQQF6TEoqa+5fkPIk/lnBGoORXfX1paMcm07uDVje+QoIDUsg7LYkxbRzw59HIAzyZ8VWbOPyYP+CoYkBgALRluoHWIrdPZV4yraSzA6/ju/5FdMY8hRmMsEzzCORA87BU0wpJUcUpOhGxZow7PHAdvRd54SX9YVWwkAIpzRxPcFqpkte4815XvO/QaVMg6q76sw3inAXk6RrtWC73fL8+bSu3mvnun0WzFdvKt37jz4/R5kMZiSN6cHgN6KuhF1J9HhAlwe0k/WcsKgQbIN1+e8jH9XHUc+CS5rj3sC3k82QVzESwv12kl6QE6SHTrkqZOiHkPyS0EiwwYIcv4RA+yLqgAgotfulMmw8piS/GQN9iOxZ2YltDfBtajb5/5dCuzhmxklBV7jf0uZgaIMMCitc/3z0JeF4AmzC/3EVzi0v403+tmUD/d0MfuvB62NIl+7LaEx1mnfiEQeaJdknDZetIfHXE47qS50/7Xh1wfeFw0Ur5vhgXpdXUpaMYoF8=
  - GCR_HOSTNAME=us.gcr.io
  - GCP_PROJECT_ID=superego-173310
  - GCP_PROJECT_NAME=superego
  - IMAGE_NAME=superego
  - GCP_COMPUTE_ZONE=us-central1-a
  - GCP_CLUSTER_NAME=superego-cluster
before_install:
- openssl aes-256-cbc -K $encrypted_457358ef82be_key -iv $encrypted_457358ef82be_iv
  -in superego-b60ee40757c8.json.enc -out ./cmd/superego/superego-b60ee40757c8.json
  -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
- gcloud auth activate-service-account --key-file ./cmd/superego/superego-b60ee40757c8.json
install:
- go get -t ./...
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- gcloud config set project $GCP_PROJECT_ID
script:
- go test -v -covermode=count -coverprofile=coverage.out
- "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN"
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "dev";
  fi`
- docker build -t ${GCR_HOSTNAME}/${GCP_PROJECT_ID}/${IMAGE_NAME}:${TAG} ./cmd/superego
after_success:
- gcloud docker -- push ${GCR_HOSTNAME}/${GCP_PROJECT_ID}/${IMAGE_NAME}:${TAG}
notifications:
  slack:
    secure: GoHaeIErGFR0wbtMDYHt57cd6Bllw9DLrLr3lAU5Rv0zAp8PUcAIecYsbYcy2BisS/jUYdcqmxX2aP6KZTQXEmy7sAJOYcIvZ/6Mnep472o+jA5ymHbn3Hbx6mxor/XZ65pgkggni1DhRHYZg2WjUaKk5Qziutb8WRbZNOZ4R7wXEBLbW00pAQuqwDjS8eKnXBtkDicGi6V02VSuK029N/gGy8Lot+kaje+pmgeU5V2Py01zC+cKivkvDtjyhsL1Eb7g7XKN0q42M0c3YOnwVh/6WxlSu8pOtLkimGhzH+/WzSdSItmxYgWTQpjj0zmcWzt715nHk4ngteGc5h2SRE0eW4GonNMfSOle+aJtYV09GKX/7QRmv0M/wjEA8IMvkKrHOAMQOxTqJqBxwgk9we+N6FURzAIvtyt6vNEKoWGDfr+2lEWnS5Te9eXH1RIYmRhRJADoCtx98iGstK9YF7OsCa9iZ7STiCxasChcoDjAQFFN7EgR26gjcU0NqHQLqElPxCyqeyL5mF/2dJm/k4C1YOJVwtX71GSZlC+PzKzWsY+I1hrhwap1FAr8GJV43U8dhd7UR5oAubN9TohTND4O+7CyJatycqDS5QTZHl74kuhUEwVfcXQCi0heCw4CUWL1zTcQL5cdhVzVy4gTJkMRunamH8LcyFMH/D8bg9U=
