apiVersion: apps/v1
kind: Deployment
metadata:
  name: superego
spec:
  selector:
    matchLabels:
      app: superego
  replicas: 3
  template:
    metadata:
      labels:
        app: superego
    spec:
      containers:
      - name: superego
        image: benkim/superego:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
